#!/bin/bash
# Posts this month's researched major gifts to your live Frankly Inspired OS.
# Run this from a Mac Terminal (or any machine with internet access and curl installed):
#   bash 2026-09-24b-post-gifts.sh
set -e

curl -sS -X POST https://frankly-inspired-os.onrender.com/api/admin/gifts \
  -H "Content-Type: application/json" \
  -H "X-Admin-Token: 81e4cff36d2c8e6267991872a209e2617a3882eb6e33b03d" \
  -d @- << 'PAYLOAD_EOF'
{"items":[
{"id":"gift-2026-09-24-university-of-oregon","donor":"Phil and Penny Knight","org":"University of Oregon","state":"OR","category":"education","amount":1000000000,"headline":"Knights pledge $1 billion to build Oregon's first full undergraduate engineering college","summary":"The gift brings the Knights' total commitment to the Knight Campus to more than $2 billion and is described as the largest known gift to a U.S. public flagship university.","source":"Fortune","url":"https://fortune.com/2026/09/24/billionaire-nike-cofounder-phil-knight-gives-1-billion-to-university-of-oregon-no-time-to-abandon-higher-education/","announcedAt":"2026-09-24","giftType":"Multi-year pledge","restriction":"Capital / naming","impact":"Builds University of Oregon's first full undergraduate engineering program (previously minors and grad-level only); a roughly decade-long project.","trendSignal":"Comes as the administration proposes roughly 57% cuts to NSF research funding; Knight framed the gift explicitly as billionaires stepping in where federal support for research universities is receding, following his own $1.1B Providence and $2B OHSU cancer gifts this year.","playbook":"A long-cultivated, multi-decade donor relationship (this is the Knights' third nine-figure-plus gift to the same campus since 2016) let the university go back to the same donor with a bigger, more strategic ask once a real capability gap (no undergrad engineering) was named plainly.","higherEd":true},
{"id":"gift-2026-09-22-indiana-university","donor":"Jeff and Benita Thomasson","org":"Indiana University (Kelley School of Business and Lilly Family School of Philanthropy)","state":"IN","category":"education","amount":100000000,"headline":"$100 million gift renames Kelley's graduate business school, endows a philanthropy scholarship","summary":"$95M funds graduate business education and endowed faculty roles; $5M establishes the Thomasson Scholarship for philanthropy and nonprofit-management students at the Lilly Family School of Philanthropy.","source":"Fortune","url":"https://fortune.com/2026/09/22/jeff-benita-thomasson-indiana-university-100-million-gift-mba-grad-school-philanthropy/","announcedAt":"2026-09-22","giftType":"Outright cash gift","restriction":"Capital / naming","impact":"Graduate business education, endowed faculty positions, and a dedicated scholarship for students studying philanthropy and nonprofit management.","trendSignal":"A self-made donor (modest background, MBA paid for by an employer) giving back to the specific program that launched his career, landing even as public confidence in higher ed and MBA value both face real headwinds (confidence down from 57% to 38% since 2015).","playbook":"The ask paired a big naming gift the donor's own career justified with a small, mission-aligned add-on (the philanthropy scholarship) that gave the gift a second story beyond 'successful alum writes a check.'","higherEd":true},
{"id":"gift-2026-09-18-university-of-st-thomas","donor":"Ciresi Walburn Foundation and the Michael V. and Ann C. Ciresi Foundation","org":"University of St. Thomas (Minnesota)","state":"MN","category":"education","amount":82000000,"headline":"$82 million gift funds first-generation and leadership programs at St. Thomas","summary":"Establishes the Ciresi Walburn Leadership Fellows Program in perpetuity (up to $70,000 over four years per low-income, service-minded student), plus a new Center for First-Generation Students and a Center for Leadership.","source":"Inside Higher Ed","url":"https://www.insidehighered.com/news/business/fundraising/2026/09/18/private-minn-university-receive-82m-first-gen-programs","announcedAt":"2026-09-18","giftType":"Endowment gift","restriction":"Endowment","impact":"Perpetual scholarship funding for low-income, first-generation students plus two new dedicated support centers.","trendSignal":"A mega-gift explicitly targeted at access and first-generation students rather than a building or school renaming, a useful counter-example to the naming-gift pattern in the two entries above it.","playbook":"Two family foundations with a long relationship to the same institution combined behind one named, perpetual program rather than each funding a separate smaller initiative, concentrating both impact and donor recognition in one place.","higherEd":true},
{"id":"gift-2026-09-11-ucla-reagan-medical-center","donor":"Laurie and Steven Gordon","org":"Ronald Reagan UCLA Medical Center","state":"CA","category":"health","amount":20000000,"headline":"$20 million gift adds 103 beds to Ronald Reagan UCLA Medical Center","summary":"Funds a renovated fourth-floor pavilion adding adult and pediatric critical and acute care beds, a 23% capacity increase, supporting cardiac, transplant, stroke, and psychiatric emergency care.","source":"Hoodline","url":"https://hoodline.com/2026/09/westwood-couple-s-20m-gift-adds-103-beds-to-ucla-reagan-medical-center/","announcedAt":"2026-09-11","giftType":"Campaign lead gift","restriction":"Capital / naming","impact":"Adds 103 critical and acute care beds, a 23% capacity increase, via a renamed, renovated hospital pavilion.","trendSignal":"A facility-capacity gift at a major academic medical center, distinct from the research and cancer mega-gifts dominating health philanthropy headlines this year, a reminder plenty of large healthcare gifts are still about beds and buildings, not research.","playbook":"A named local couple gave to solve a concrete, countable capacity problem (a specific bed shortage) rather than a broad mission ask, a model for pairing a capital case with a hard number a donor can picture funding directly.","higherEd":false},
{"id":"gift-2026-08-21-uncf-dimon-fund","donor":"James and Judith K. Dimon Foundation","org":"UNCF (Dimon Fund to Advance Economic Opportunity, 12 member HBCUs)","state":"","category":"education","amount":12000000,"headline":"Dimon Foundation gives UNCF $12 million to endow 12 HBCUs at $1 million each","summary":"Establishes the Dimon Fund to Advance Economic Opportunity, providing permanent $1 million endowments to 12 UNCF member HBCUs selected for their record preparing educators, nurses, and other healthcare professionals.","source":"TheGrio","url":"https://thegrio.com/2026/08/21/dimon-foundation-hbcu-gift-12-million-uncf/","announcedAt":"2026-08-21","giftType":"Endowment gift","restriction":"Endowment","impact":"Permanent $1 million endowment at each of 12 HBCUs, targeted at career-connected fields (education, nursing, healthcare).","trendSignal":"A corporate-leader family foundation (JPMorgan Chase's CEO) routing a multi-institution HBCU gift through a national intermediary (UNCF) rather than negotiating with each school directly, a distribution model worth noting for any client weighing a multi-recipient gift.","playbook":"Working through an established intermediary (UNCF) let one $12 million gift reach 12 institutions with one negotiation, one announcement, and one set of terms, a model worth offering a donor weighing several smaller recipients directly.","higherEd":true}
]}
PAYLOAD_EOF

echo
echo "Done. Open the Giving Landscape > Gift ticker tab in the app to confirm."
